### ISSUE TITLE
Fullscreen ending part needed

### ISSUE THREAD

**Issue by Xetera** [moedevs/hifumi.io#26]
We probably want something like what [satania.moe](https://satania.moe) has for its very last part. Figured we could use this image (or something more high res) which I totally didn't get from the post of that guy getting banned from reddit 
![](https://i.imgur.com/kKy3hrE.jpg)

**Comment by jvyden420** [comment]
![bgforhifumi-io](https://user-images.githubusercontent.com/40577357/52182271-8e405000-27c9-11e9-9e73-64e87cd0dfda.png)
I ran it through waifu2x, is good?

**Comment by itsaferbie** [comment]
I was able to get it even smaller by slightly reducing quality of export, but no significant degradation happened. It is now 570KB

**Comment by Xetera** [comment]
implemented
